version: '3'
services:
  opensearch-node1:
    image: gsingers/opensearch-learning-to-rank:2.1.0
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - http.max_content_length=1000mb
      - "OPENSEARCH_JAVA_OPTS=-Xms4G -Xmx4G"

    volumes:
      - opensearch-data1:/usr/share/opensearch/data  #todo: figure this out so we can have persistent storage
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net


volumes:
  opensearch-data1:

networks:
  opensearch-net:
    driver: bridge
